;; Title: Incofidente
;; Project: inconfidente
;; Version: 0.0.0
;; Author: gbrlgn
;; License: Anthropophagic GPLv3

(deftheme inconfidente "LIBERTAS QUAE SERA TAMEN")

(defgroup inconfidente nil
  "Inconfidente theme customizations.
  The theme has to be reloaded after changing anything in this group."
  :group 'faces)

(defcustom inconfidente-comment-brightness 10
  "Allows to define a custom comment color brightness with percentage adjustments from 0% - 20%."
  :type 'integer
  :group 'inconfidente)

(defcustom inconfidente-uniform-mode-lines nil
  "Enables uniform activate- and inactive mode lines using 'inconfidente3' as background."
  :type 'boolean
  :group 'inconfidente)

;;;; Color Constants
(let ((class '((class color) (min-colors 89)))
  (inconfidente0 "#242424")
  (inconfidente1 "#1e1e1e")
  (inconfidente2 "#242424")
  (inconfidente3 "#242424")
  (inconfidente4 "#a89f93")
  (inconfidente5 "#a89f93")
  (inconfidente6 "#AFA89E")
  (inconfidente7 "#4d6664")
  (inconfidente8 "#4d6664")
  (inconfidente9 "#4e5366")
  (inconfidente10 "#4e5366")
  (inconfidente11 "#664949")
  (inconfidente12 "#6d614a")
  (inconfidente13 "#6d614a")
  (inconfidente14 "#56664c")
  (inconfidente15 "#664d61")
  (inconfidente-annotation "#6d614a")
  (inconfidente-attribute "#4d6664")
  (inconfidente-class "#4d6664")
  (inconfidente-comment "#444444")
  (inconfidente-escape "#6d614a")
  (inconfidente-method "#4d6664")
  (inconfidente-keyword "#4e5366")
  (inconfidente-numeric "#664d61")
  (inconfidente-operator "#4e5366")
  (inconfidente-preprocessor "#4e5366")
  (inconfidente-punctuation "#7F796F")
  (inconfidente-regexp "#6d614a")
  (inconfidente-string "#56664c")
  (inconfidente-tag "#4e5366")
  (inconfidente-variable "#7F796F")
  (inconfidente-region-highlight-foreground "#d1cdc7")
  (inconfidente-region-highlight-background "#303030")
  (inconfidente-uniform-mode-lines-background "#1e1e1e"))

;;;; +------------+
;;;; + Core Faces +
;;;; +------------+
  (custom-theme-set-faces
    'inconfidente
    ;; +--- Base ---+
    `(bold ((,class (:weight bold))))
    `(bold-italic ((,class (:weight bold :slant italic))))
    `(default ((,class (:foreground ,inconfidente4 :background ,inconfidente0))))
    `(error ((,class (:foreground ,inconfidente11 :weight bold))))
    `(escape-glyph ((,class (:foreground ,inconfidente12))))
    `(font-lock-builtin-face ((,class (:foreground ,inconfidente9))))
    `(font-lock-comment-face ((,class (:foreground ,inconfidente-comment))))
    `(font-lock-comment-delimiter-face ((,class (:foreground ,inconfidente-comment))))
    `(font-lock-constant-face ((,class (:foreground ,inconfidente9))))
    `(font-lock-doc-face ((,class (:foreground ,inconfidente-comment))))
    `(font-lock-function-name-face ((,class (:foreground ,inconfidente8))))
    `(font-lock-keyword-face ((,class (:foreground ,inconfidente9))))
    `(font-lock-negation-char-face ((,class (:foreground ,inconfidente9))))
    `(font-lock-preprocessor-face ((,class (:foreground ,inconfidente10 :weight bold))))
    `(font-lock-reference-face ((,class (:foreground ,inconfidente9))))
    `(font-lock-regexp-grouping-backslash ((,class (:foreground ,inconfidente13))))
    `(font-lock-regexp-grouping-construct ((,class (:foreground ,inconfidente13))))
    `(font-lock-string-face ((,class (:foreground ,inconfidente14))))
    `(font-lock-type-face ((,class (:foreground ,inconfidente7))))
    `(font-lock-variable-name-face ((,class (:foreground ,inconfidente4))))
    `(font-lock-warning-face ((,class (:foreground ,inconfidente13))))
    `(italic ((,class (:slant italic))))
    `(shadow ((,class (:foreground ,inconfidente3))))
    `(underline ((,class (:underline t))))
    `(warning ((,class (:foreground ,inconfidente13 :weight bold))))

    ;; +--- Syntax ---+
    ;; > C
    `(c-annotation-face ((,class (:foreground ,inconfidente-annotation))))

    ;; > diff
    `(diff-added ((,class (:foreground ,inconfidente14))))
    `(diff-changed ((,class (:foreground ,inconfidente13))))
    `(diff-context ((,class (:inherit default))))
    `(diff-file-header ((,class (:foreground ,inconfidente8))))
    `(diff-function ((,class (:foreground ,inconfidente7))))
    `(diff-header ((,class (:foreground ,inconfidente9 :weight bold))))
    `(diff-hunk-header ((,class (:foreground ,inconfidente9 :background ,inconfidente0))))
    `(diff-indicator-added ((,class (:foreground ,inconfidente14))))
    `(diff-indicator-changed ((,class (:foreground ,inconfidente13))))
    `(diff-indicator-removed ((,class (:foreground ,inconfidente11))))
    `(diff-nonexistent ((,class (:foreground ,inconfidente11))))
    `(diff-refine-added ((,class (:foreground ,inconfidente14))))
    `(diff-refine-changed ((,class (:foreground ,inconfidente13))))
    `(diff-refine-removed ((,class (:foreground ,inconfidente11))))
    `(diff-removed ((,class (:foreground ,inconfidente11))))

    ;; +--- UI ---+
    `(border ((,class (:foreground ,inconfidente4))))
    `(buffer-menu-buffer ((,class (:foreground ,inconfidente4 :weight bold))))
    `(button ((,class (:background ,inconfidente0 :foreground ,inconfidente8 :box (:line-width 2 :color ,inconfidente4 :style sunken-button)))))
    `(completions-annotations ((,class (:foreground ,inconfidente9))))
    `(completions-common-part ((,class (:foreground ,inconfidente8 :weight bold))))
    `(completions-first-difference ((,class (:foreground ,inconfidente11))))
    `(custom-button ((,class (:background ,inconfidente0 :foreground ,inconfidente8 :box (:line-width 2 :color ,inconfidente4 :style sunken-button)))))
    `(custom-button-mouse ((,class (:background ,inconfidente4 :foreground ,inconfidente0 :box (:line-width 2 :color ,inconfidente4 :style sunken-button)))))
    `(custom-button-pressed ((,class (:background ,inconfidente6 :foreground ,inconfidente0 :box (:line-width 2 :color ,inconfidente4 :style sunken-button)))))
    `(custom-button-pressed-unraised ((,class (:background ,inconfidente4 :foreground ,inconfidente0 :box (:line-width 2 :color ,inconfidente4 :style sunken-button)))))
    `(custom-button-unraised ((,class (:background ,inconfidente0 :foreground ,inconfidente8 :box (:line-width 2 :color ,inconfidente4 :style sunken-button)))))
    `(custom-changed ((,class (:foreground ,inconfidente13))))
    `(custom-comment ((,class (:foreground ,inconfidente-comment))))
    `(custom-comment-tag ((,class (:foreground ,inconfidente7))))
    `(custom-documentation ((,class (:foreground ,inconfidente4))))
    `(custom-group-tag ((,class (:foreground ,inconfidente8 :weight bold))))
    `(custom-group-tag-1 ((,class (:foreground ,inconfidente8 :weight bold))))
    `(custom-invalid ((,class (:foreground ,inconfidente11))))
    `(custom-modified ((,class (:foreground ,inconfidente13))))
    `(custom-rogue ((,class (:foreground ,inconfidente12 :background ,inconfidente2))))
    `(custom-saved ((,class (:foreground ,inconfidente14))))
    `(custom-set ((,class (:foreground ,inconfidente8))))
    `(custom-state ((,class (:foreground ,inconfidente14))))
    `(custom-themed ((,class (:foreground ,inconfidente8 :background ,inconfidente2))))
    `(cursor ((,class (:background ,inconfidente4))))
    `(fringe ((,class (:foreground ,inconfidente4 :background ,inconfidente0))))
    `(file-name-shadow ((,class (:inherit shadow))))
    `(header-line ((,class (:foreground ,inconfidente4 :background ,inconfidente2))))
    `(help-argument-name ((,class (:foreground ,inconfidente8))))
    `(highlight ((,class (:foreground ,inconfidente8 :background ,inconfidente2))))
    `(hl-line ((,class (:background ,inconfidente1))))
    `(info-menu-star ((,class (:foreground ,inconfidente9))))
    `(isearch ((,class (:foreground ,inconfidente0 :background ,inconfidente8))))
    `(isearch-fail ((,class (:foreground ,inconfidente11))))
    `(link ((,class (:underline t))))
    `(link-visited ((,class (:underline t))))
    `(linum ((,class (:foreground ,inconfidente3 :background ,inconfidente0))))
    `(linum-relative-current-face ((,class (:foreground ,inconfidente3 :background ,inconfidente0))))
    `(match ((,class (:inherit isearch))))
    `(message-cited-text ((,class (:foreground ,inconfidente4))))
    `(message-header-cc ((,class (:foreground ,inconfidente9))))
    `(message-header-name ((,class (:foreground ,inconfidente7))))
    `(message-header-newsgroup ((,class (:foreground ,inconfidente14))))
    `(message-header-other ((,class (:foreground ,inconfidente4))))
    `(message-header-subject ((,class (:foreground ,inconfidente8))))
    `(message-header-to ((,class (:foreground ,inconfidente9))))
    `(message-header-xheader ((,class (:foreground ,inconfidente13))))
    `(message-mml ((,class (:foreground ,inconfidente10))))
    `(message-separator ((,class (:inherit shadow))))
    `(minibuffer-prompt ((,class (:foreground ,inconfidente8 :weight bold))))
    `(mm-command-output ((,class (:foreground ,inconfidente8))))
    `(mode-line ((,class (:foreground ,inconfidente8 :background ,inconfidente3))))
    `(mode-line-buffer-id ((,class (:weight bold))))
    `(mode-line-highlight ((,class (:inherit highlight))))
    `(mode-line-inactive ((,class (:foreground ,inconfidente4 :background ,inconfidente-uniform-mode-lines-background))))
    `(next-error ((,class (:inherit error))))
    `(nobreak-space ((,class (:foreground ,inconfidente3))))
    `(outline-1 ((,class (:foreground ,inconfidente8 :weight bold))))
    `(outline-2 ((,class (:inherit outline-1))))
    `(outline-3 ((,class (:inherit outline-1))))
    `(outline-4 ((,class (:inherit outline-1))))
    `(outline-5 ((,class (:inherit outline-1))))
    `(outline-6 ((,class (:inherit outline-1))))
    `(outline-7 ((,class (:inherit outline-1))))
    `(outline-8 ((,class (:inherit outline-1))))
    `(package-description ((,class (:foreground ,inconfidente4))))
    `(package-help-section-name ((,class (:foreground ,inconfidente8 :weight bold))))
    `(package-name ((,class (:foreground ,inconfidente8))))
    `(package-status-available ((,class (:foreground ,inconfidente7))))
    `(package-status-avail-obso ((,class (:foreground ,inconfidente7 :slant italic))))
    `(package-status-built-in ((,class (:foreground ,inconfidente9))))
    `(package-status-dependency ((,class (:foreground ,inconfidente8 :slant italic))))
    `(package-status-disabled ((,class (:foreground ,inconfidente3))))
    `(package-status-external ((,class (:foreground ,inconfidente12 :slant italic))))
    `(package-status-held ((,class (:foreground ,inconfidente4 :weight bold))))
    `(package-status-new ((,class (:foreground ,inconfidente14))))
    `(package-status-incompat ((,class (:foreground ,inconfidente11))))
    `(package-status-installed ((,class (:foreground ,inconfidente7 :weight bold))))
    `(package-status-unsigned ((,class (:underline ,inconfidente13))))
    `(query-replace ((,class (:foreground ,inconfidente8 :background ,inconfidente2))))
    `(region ((,class (:foreground ,inconfidente-region-highlight-foreground :background ,inconfidente-region-highlight-background))))
    `(scroll-bar ((,class (:background ,inconfidente3))))
    `(secondary-selection ((,class (:background ,inconfidente2))))

    ;; `show-paren-match-face` and `show-paren-mismatch-face` are deprecated since Emacs version 22.1 and were
    ;; removed in Emacs 25.
    ;; https://github.com/arcticicestudio/inconfidente-emacs/issues/75
    ;; http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=c430f7e23fc2c22f251ace4254e37dea1452dfc3
    ;; https://github.com/emacs-mirror/emacs/commit/c430f7e23fc2c22f251ace4254e37dea1452dfc3
    `(show-paren-match-face ((,class (:foreground ,inconfidente0 :background ,inconfidente8))))
    `(show-paren-mismatch-face ((,class (:background ,inconfidente11))))

    `(show-paren-match ((,class (:foreground ,inconfidente0 :background ,inconfidente8))))
    `(show-paren-mismatch ((,class (:background ,inconfidente11))))
    `(success ((,class (:foreground ,inconfidente14))))
    `(term ((,class (:foreground ,inconfidente4 :background ,inconfidente0))))
    `(term-color-black ((,class (:foreground ,inconfidente1 :background ,inconfidente1))))
    `(term-color-white ((,class (:foreground ,inconfidente5 :background ,inconfidente5))))
    `(term-color-cyan ((,class (:foreground ,inconfidente7 :background ,inconfidente7))))
    `(term-color-blue ((,class (:foreground ,inconfidente8 :background ,inconfidente8))))
    `(term-color-red ((,class (:foreground ,inconfidente11 :background ,inconfidente11))))
    `(term-color-yellow ((,class (:foreground ,inconfidente13 :background ,inconfidente13))))
    `(term-color-green ((,class (:foreground ,inconfidente14 :background ,inconfidente14))))
    `(term-color-magenta ((,class (:foreground ,inconfidente15 :background ,inconfidente15))))
    `(tool-bar ((,class (:foreground ,inconfidente4 :background ,inconfidente3))))
    `(tooltip ((,class (:foreground ,inconfidente0 :background ,inconfidente4))))
    `(trailing-whitespace ((,class (:foreground ,inconfidente3))))
    `(tty-menu-disabled-face ((,class (:foreground ,inconfidente1))))
    `(tty-menu-enabled-face ((,class (:background ,inconfidente2 foreground ,inconfidente4))))
    `(tty-menu-selected-face ((,class (:foreground ,inconfidente8 :underline t))))
    `(undo-tree-visualizer-current-face ((,class (:foreground ,inconfidente8))))
    `(undo-tree-visualizer-default-face ((,class (:foreground ,inconfidente4))))
    `(undo-tree-visualizer-unmodified-face ((,class (:foreground ,inconfidente4))))
    `(undo-tree-visualizer-register-face ((,class (:foreground ,inconfidente9))))
    `(vc-conflict-state ((,class (:foreground ,inconfidente12))))
    `(vc-edited-state ((,class (:foreground ,inconfidente13))))
    `(vc-locally-added-state ((,class (:underline ,inconfidente14))))
    `(vc-locked-state ((,class (:foreground ,inconfidente10))))
    `(vc-missing-state ((,class (:foreground ,inconfidente11))))
    `(vc-needs-update-state ((,class (:foreground ,inconfidente12))))
    `(vc-removed-state ((,class (:foreground ,inconfidente11))))
    `(vc-state-base ((,class (:foreground ,inconfidente4))))
    `(vc-up-to-date-state ((,class (:foreground ,inconfidente8))))
    `(vertical-border ((,class (:foreground ,inconfidente2))))
    `(which-func ((,class (:foreground ,inconfidente8))))
    `(whitespace-big-indent ((,class (:foreground ,inconfidente3 :background ,inconfidente0))))
    `(whitespace-empty ((,class (:foreground ,inconfidente3 :background ,inconfidente0))))
    `(whitespace-hspace ((,class (:foreground ,inconfidente3 :background ,inconfidente0))))
    `(whitespace-indentation ((,class (:foreground ,inconfidente3 :background ,inconfidente0))))
    `(whitespace-line ((,class (:background ,inconfidente0))))
    `(whitespace-newline ((,class (:foreground ,inconfidente3 :background ,inconfidente0))))
    `(whitespace-space ((,class (:foreground ,inconfidente3 :background ,inconfidente0))))
    `(whitespace-space-after-tab ((,class (:foreground ,inconfidente3 :background ,inconfidente0))))
    `(whitespace-space-before-tab ((,class (:foreground ,inconfidente3 :background ,inconfidente0))))
    `(whitespace-tab ((,class (:foreground ,inconfidente3 :background ,inconfidente0))))
    `(whitespace-trailing ((,class (:inherit trailing-whitespace))))
    `(widget-button-pressed ((,class (:foreground ,inconfidente9 :background ,inconfidente1))))
    `(widget-documentation ((,class (:foreground ,inconfidente4))))
    `(widget-field ((,class (:background ,inconfidente2 :foreground ,inconfidente4))))
    `(widget-single-line-field ((,class (:background ,inconfidente2 :foreground ,inconfidente4))))
    `(window-divider ((,class (:background ,inconfidente3))))
    `(window-divider-first-pixel ((,class (:background ,inconfidente3))))
    `(window-divider-last-pixel ((,class (:background ,inconfidente3))))

    ;;;; +-----------------+
    ;;;; + Package Support +
    ;;;; +-----------------+
    ;; +--- Syntax ---+
    ;; > Auctex
    `(font-latex-bold-face ((,class (:inherit bold))))
    `(font-latex-italic-face ((,class (:inherit italic))))
    `(font-latex-math-face ((,class (:foreground ,inconfidente8))))
    `(font-latex-sectioning-0-face ((,class (:foreground ,inconfidente8 :weight bold))))
    `(font-latex-sectioning-1-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-sectioning-2-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-sectioning-3-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-sectioning-4-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-sectioning-5-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-script-char-face ((,class (:inherit font-lock-warning-face))))
    `(font-latex-string-face ((,class (:inherit font-lock-string-face))))
    `(font-latex-warning-face ((,class (:inherit font-lock-warning-face))))

    ;; > Elixir
    `(elixir-attribute-face ((,class (:foreground ,inconfidente-annotation))))
    `(elixir-atom-face ((,class (:foreground ,inconfidente4 :weight bold))))

    ;; > Enhanced Ruby
    `(enh-ruby-heredoc-delimiter-face ((,class (:foreground ,inconfidente14))))
    `(enh-ruby-op-face ((,class (:foreground ,inconfidente9))))
    `(enh-ruby-regexp-delimiter-face ((,class (:foreground ,inconfidente13))))
    `(enh-ruby-regexp-face ((,class (:foreground ,inconfidente13))))
    `(enh-ruby-string-delimiter-face ((,class (:foreground ,inconfidente14))))
    `(erm-syn-errline ((,class (:foreground ,inconfidente11 :underline t))))
    `(erm-syn-warnline ((,class (:foreground ,inconfidente13 :underline t))))

    ;; > Java Development Environment for Emacs
    `(jdee-db-active-breakpoint-face ((,class (:background ,inconfidente2 :weight bold))))
    `(jdee-bug-breakpoint-cursor ((,class (:background ,inconfidente2))))
    `(jdee-db-requested-breakpoint-face ((,class (:foreground ,inconfidente13 :background ,inconfidente2 :weight bold))))
    `(jdee-db-spec-breakpoint-face ((,class (:foreground ,inconfidente14 :background ,inconfidente2 :weight bold))))
    `(jdee-font-lock-api-face ((,class (:foreground ,inconfidente4))))
    `(jdee-font-lock-code-face ((,class (:slant italic))))
    `(jdee-font-lock-constant-face ((,class (:foreground ,inconfidente-keyword))))
    `(jdee-font-lock-constructor-face ((,class (:foreground ,inconfidente-method))))
    `(jdee-font-lock-doc-tag-face ((,class (:foreground ,inconfidente7))))
    `(jdee-font-lock-link-face ((,class (:underline t))))
    `(jdee-font-lock-modifier-face ((,class (:foreground ,inconfidente-keyword))))
    `(jdee-font-lock-number-face ((,class (:foreground ,inconfidente-numeric))))
    `(jdee-font-lock-operator-fac ((,class (:foreground ,inconfidente-operator))))
    `(jdee-font-lock-package-face ((,class (:foreground ,inconfidente-class))))
    `(jdee-font-lock-pre-face ((,class (:foreground ,inconfidente-comment :slant italic))))
    `(jdee-font-lock-private-face ((,class (:foreground ,inconfidente-keyword))))
    `(jdee-font-lock-public-face ((,class (:foreground ,inconfidente-keyword))))
    `(jdee-font-lock-variable-face ((,class (:foreground ,inconfidente-variable))))

    ;; > JavaScript 2
    `(js2-function-call ((,class (:foreground ,inconfidente8))))
    `(js2-private-function-call ((,class (:foreground ,inconfidente8))))
    `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,inconfidente6))))
    `(js2-jsdoc-html-tag-name ((,class (:foreground ,inconfidente9))))
    `(js2-external-variable ((,class (:foreground ,inconfidente4))))
    `(js2-function-param ((,class (:foreground ,inconfidente4))))
    `(js2-jsdoc-value ((,class (:foreground ,inconfidente-comment))))
    `(js2-jsdoc-tag ((,class (:foreground ,inconfidente7))))
    `(js2-jsdoc-type ((,class (:foreground ,inconfidente7))))
    `(js2-private-member ((,class (:foreground ,inconfidente4))))
    `(js2-object-property ((,class (:foreground ,inconfidente4))))
    `(js2-error ((,class (:foreground ,inconfidente11))))
    `(js2-warning ((,class (:foreground ,inconfidente13))))
    `(js2-instance-member ((,class (:foreground ,inconfidente4))))

    ;; > JavaScript 3
    `(js3-error-face ((,class (:foreground ,inconfidente11))))
    `(js3-external-variable-face ((,class (:foreground ,inconfidente4))))
    `(js3-function-param-face ((,class (:foreground ,inconfidente4))))
    `(js3-instance-member-face ((,class (:foreground ,inconfidente4))))
    `(js3-jsdoc-html-tag-delimiter-face ((,class (:foreground ,inconfidente6))))
    `(js3-jsdoc-html-tag-name-face ((,class (:foreground ,inconfidente9))))
    `(js3-jsdoc-tag-face ((,class (:foreground ,inconfidente9))))
    `(js3-jsdoc-type-face ((,class (:foreground ,inconfidente7))))
    `(js3-jsdoc-value-face ((,class (:foreground ,inconfidente4))))
    `(js3-magic-paren-face ((,class (:inherit show-paren-match-face))))
    `(js3-private-function-call-face ((,class (:foreground ,inconfidente8))))
    `(js3-private-member-face ((,class (:foreground ,inconfidente4))))
    `(js3-warning-face ((,class (:foreground ,inconfidente13))))

    ;; > Markdown
    `(markdown-blockquote-face ((,class (:foreground ,inconfidente-comment))))
    `(markdown-bold-face ((,class (:inherit bold))))
    `(markdown-header-face-1 ((,class (:foreground ,inconfidente8))))
    `(markdown-header-face-2 ((,class (:foreground ,inconfidente8))))
    `(markdown-header-face-3 ((,class (:foreground ,inconfidente8))))
    `(markdown-header-face-4 ((,class (:foreground ,inconfidente8))))
    `(markdown-header-face-5 ((,class (:foreground ,inconfidente8))))
    `(markdown-header-face-6 ((,class (:foreground ,inconfidente8))))
    `(markdown-inline-code-face ((,class (:foreground ,inconfidente7))))
    `(markdown-italic-face ((,class (:inherit italic))))
    `(markdown-link-face ((,class (:foreground ,inconfidente8))))
    `(markdown-markup-face ((,class (:foreground ,inconfidente9))))
    `(markdown-reference-face ((,class (:inherit markdown-link-face))))
    `(markdown-url-face ((,class (:foreground ,inconfidente4 :underline t))))

    ;; > Rainbow Delimeters
    `(rainbow-delimiters-depth-1-face ((,class :foreground ,inconfidente7)))
    `(rainbow-delimiters-depth-2-face ((,class :foreground ,inconfidente8)))
    `(rainbow-delimiters-depth-3-face ((,class :foreground ,inconfidente9)))
    `(rainbow-delimiters-depth-4-face ((,class :foreground ,inconfidente10)))
    `(rainbow-delimiters-depth-5-face ((,class :foreground ,inconfidente12)))
    `(rainbow-delimiters-depth-6-face ((,class :foreground ,inconfidente13)))
    `(rainbow-delimiters-depth-7-face ((,class :foreground ,inconfidente14)))
    `(rainbow-delimiters-depth-8-face ((,class :foreground ,inconfidente15)))
    `(rainbow-delimiters-unmatched-face ((,class :foreground ,inconfidente11)))

    ;; > Web Mode
    `(web-mode-attr-tag-custom-face ((,class (:foreground ,inconfidente-attribute))))
    `(web-mode-builtin-face ((,class (:foreground ,inconfidente-keyword))))
    `(web-mode-comment-face ((,class (:foreground ,inconfidente-comment))))
    `(web-mode-comment-keyword-face ((,class (:foreground ,inconfidente-comment))))
    `(web-mode-constant-face ((,class (:foreground ,inconfidente-variable))))
    `(web-mode-css-at-rule-face ((,class (:foreground ,inconfidente-annotation))))
    `(web-mode-css-function-face ((,class (:foreground ,inconfidente-method))))
    `(web-mode-css-property-name-face ((,class (:foreground ,inconfidente-keyword))))
    `(web-mode-css-pseudo-class-face ((,class (:foreground ,inconfidente-class))))
    `(web-mode-css-selector-face ((,class (:foreground ,inconfidente-keyword))))
    `(web-mode-css-string-face ((,class (:foreground ,inconfidente-string))))
    `(web-mode-doctype-face ((,class (:foreground ,inconfidente-preprocessor))))
    `(web-mode-function-call-face ((,class (:foreground ,inconfidente-method))))
    `(web-mode-function-name-face ((,class (:foreground ,inconfidente-method))))
    `(web-mode-html-attr-name-face ((,class (:foreground ,inconfidente-attribute))))
    `(web-mode-html-attr-equal-face ((,class (:foreground ,inconfidente-punctuation))))
    `(web-mode-html-attr-value-face ((,class (:foreground ,inconfidente-string))))
    `(web-mode-html-entity-face ((,class (:foreground ,inconfidente-keyword))))
    `(web-mode-html-tag-bracket-face ((,class (:foreground ,inconfidente-punctuation))))
    `(web-mode-html-tag-custom-face ((,class (:foreground ,inconfidente-tag))))
    `(web-mode-html-tag-face ((,class (:foreground ,inconfidente-tag))))
    `(web-mode-html-tag-namespaced-face ((,class (:foreground ,inconfidente-keyword))))
    `(web-mode-json-key-face ((,class (:foreground ,inconfidente-class))))
    `(web-mode-json-string-face ((,class (:foreground ,inconfidente-string))))
    `(web-mode-keyword-face ((,class (:foreground ,inconfidente-keyword))))
    `(web-mode-preprocessor-face ((,class (:foreground ,inconfidente-preprocessor))))
    `(web-mode-string-face ((,class (:foreground ,inconfidente-string))))
    `(web-mode-symbol-face ((,class (:foreground ,inconfidente-variable))))
    `(web-mode-type-face ((,class (:foreground ,inconfidente-class))))
    `(web-mode-warning-face ((,class (:inherit ,font-lock-warning-face))))
    `(web-mode-variable-name-face ((,class (:foreground ,inconfidente-variable))))

    ;; +--- UI ---+
    ;; > Anzu
    `(anzu-mode-line ((,class (:foreground, inconfidente8))))
    `(anzu-mode-line-no-match ((,class (:foreground, inconfidente11))))

    ;; > Avy
    `(avy-lead-face ((,class (:background ,inconfidente11 :foreground ,inconfidente5))))
    `(avy-lead-face-0 ((,class (:background ,inconfidente10 :foreground ,inconfidente5))))
    `(avy-lead-face-1 ((,class (:background ,inconfidente3 :foreground ,inconfidente5))))
    `(avy-lead-face-2 ((,class (:background ,inconfidente15 :foreground ,inconfidente5))))

    ;; > Company
    `(company-echo-common ((,class (:foreground ,inconfidente0 :background ,inconfidente4))))
    `(company-preview ((,class (:foreground ,inconfidente4 :background ,inconfidente10))))
    `(company-preview-common ((,class (:foreground ,inconfidente0 :background ,inconfidente8))))
    `(company-preview-search ((,class (:foreground ,inconfidente0 :background ,inconfidente8))))
    `(company-scrollbar-bg ((,class (:foreground ,inconfidente1 :background ,inconfidente1))))
    `(company-scrollbar-fg ((,class (:foreground ,inconfidente2 :background ,inconfidente2))))
    `(company-template-field ((,class (:foreground ,inconfidente0 :background ,inconfidente7))))
    `(company-tooltip ((,class (:foreground ,inconfidente4 :background ,inconfidente2))))
    `(company-tooltip-annotation ((,class (:foreground ,inconfidente12))))
    `(company-tooltip-annotation-selection ((,class (:foreground ,inconfidente12 :weight bold))))
    `(company-tooltip-common ((,class (:foreground ,inconfidente8))))
    `(company-tooltip-common-selection ((,class (:foreground ,inconfidente8 :background ,inconfidente3))))
    `(company-tooltip-mouse ((,class (:inherit highlight))))
    `(company-tooltip-selection ((,class (:background ,inconfidente3 :weight bold))))

    ;; > diff-hl
   `(diff-hl-change ((,class (:background ,inconfidente13))))
   `(diff-hl-insert ((,class (:background ,inconfidente14))))
   `(diff-hl-delete ((,class (:background ,inconfidente11))))
   
    ;; > Evil
    `(evil-ex-info ((,class (:foreground ,inconfidente8))))
    `(evil-ex-substitute-replacement ((,class (:foreground ,inconfidente9))))
    `(evil-ex-substitute-matches ((,class (:inherit isearch))))

    ;; > Flycheck
    `(flycheck-error ((,class (:underline (:style wave :color ,inconfidente11)))))
    `(flycheck-fringe-error ((,class (:foreground ,inconfidente11 :weight bold))))
    `(flycheck-fringe-info ((,class (:foreground ,inconfidente8 :weight bold))))
    `(flycheck-fringe-warning ((,class (:foreground ,inconfidente13 :weight bold))))
    `(flycheck-info ((,class (:underline (:style wave :color ,inconfidente8)))))
    `(flycheck-warning ((,class (:underline (:style wave :color ,inconfidente13)))))

    ;; > Git Gutter
    `(git-gutter:modified ((,class (:foreground ,inconfidente13))))
    `(git-gutter:added ((,class (:foreground ,inconfidente14))))
    `(git-gutter:deleted ((,class (:foreground ,inconfidente11))))

    ;; > Git Gutter Plus
    `(git-gutter+-modified ((,class (:foreground ,inconfidente13))))
    `(git-gutter+-added ((,class (:foreground ,inconfidente14))))
    `(git-gutter+-deleted ((,class (:foreground ,inconfidente11))))

    ;; > Helm
    `(helm-bookmark-addressbook ((,class (:foreground ,inconfidente7))))
    `(helm-bookmark-directory ((,class (:foreground ,inconfidente9))))
    `(helm-bookmark-file ((,class (:foreground ,inconfidente8))))
    `(helm-bookmark-gnus ((,class (:foreground ,inconfidente10))))
    `(helm-bookmark-info ((,class (:foreground ,inconfidente14))))
    `(helm-bookmark-man ((,class (:foreground ,inconfidente4))))
    `(helm-bookmark-w3m ((,class (:foreground ,inconfidente9))))
    `(helm-buffer-directory ((,class (:foreground ,inconfidente9))))
    `(helm-buffer-file ((,class (:foreground ,inconfidente8))))
    `(helm-buffer-not-saved ((,class (:foreground ,inconfidente13))))
    `(helm-buffer-process ((,class (:foreground ,inconfidente10))))
    `(helm-candidate-number ((,class (:foreground ,inconfidente4 :weight bold))))
    `(helm-candidate-number-suspended ((,class (:foreground ,inconfidente4))))
    `(helm-ff-directory ((,class (:foreground ,inconfidente9 :weight bold))))
    `(helm-ff-dirs ((,class (:foreground ,inconfidente9))))
    `(helm-ff-dotted-director ((,class (:foreground ,inconfidente9 :underline t))))
    `(helm-ff-dotted-symlink-director ((,class (:foreground ,inconfidente7 :weight bold))))
    `(helm-ff-executable ((,class (:foreground ,inconfidente8))))
    `(helm-ff-file ((,class (:foreground ,inconfidente4))))
    `(helm-ff-invalid-symlink ((,class (:foreground ,inconfidente11 :weight bold))))
    `(helm-ff-prefix ((,class (:foreground ,inconfidente0 :background ,inconfidente9))))
    `(helm-ff-symlink ((,class (:foreground ,inconfidente7))))
    `(helm-grep-cmd-line ((,class (:foreground ,inconfidente4 :background ,inconfidente0))))
    `(helm-grep-file ((,class (:foreground ,inconfidente8))))
    `(helm-grep-finish ((,class (:foreground ,inconfidente5))))
    `(helm-grep-lineno ((,class (:foreground ,inconfidente4))))
    `(helm-grep-match ((,class (:inherit isearch))))
    `(helm-grep-running ((,class (:foreground ,inconfidente8))))
    `(helm-header ((,class (:foreground ,inconfidente9 :background ,inconfidente2))))
    `(helm-header-line-left-margin ((,class (:foreground ,inconfidente9 :background ,inconfidente2))))
    `(helm-history-deleted ((,class (:foreground ,inconfidente11))))
    `(helm-history-remote ((,class (:foreground ,inconfidente4))))
    `(helm-lisp-completion-info ((,class (:foreground ,inconfidente4 :weight bold))))
    `(helm-lisp-show-completion ((,class (:inherit isearch))))
    `(helm-locate-finish ((,class (:foreground ,inconfidente14))))
    `(helm-match ((,class (:foreground ,inconfidente8))))
    `(helm-match-item ((,class (:inherit isearch))))
    `(helm-moccur-buffer ((,class (:foreground ,inconfidente8))))
    `(helm-resume-need-update ((,class (:foreground ,inconfidente0 :background ,inconfidente13))))
    `(helm-selection ((,class (:inherit highlight))))
    `(helm-selection-line ((,class (:background ,inconfidente2))))
    `(helm-source-header ((,class (:height 1.44 :foreground ,inconfidente8 :background ,inconfidente2))))
    `(helm-swoop-line-number-face ((,class (:foreground ,inconfidente4 :background ,inconfidente0))))
    `(helm-swoop-target-word-face ((,class (:foreground ,inconfidente0 :background ,inconfidente7))))
    `(helm-swoop-target-line-face ((,class (:background ,inconfidente13 :foreground ,inconfidente3))))
    `(helm-swoop-target-line-block-face ((,class (:background ,inconfidente13 :foreground ,inconfidente3))))
    `(helm-separator ((,class (:background ,inconfidente2))))
    `(helm-visible-mark ((,class (:background ,inconfidente2))))

    ;; > Magit
    `(magit-branch ((,class (:foreground ,inconfidente7 :weight bold))))
    `(magit-diff-context-highlight ((,class (:background ,inconfidente2))))
    `(magit-diff-file-header ((,class (:foreground ,inconfidente8 :box (:color ,inconfidente8)))))
    `(magit-diffstat-added ((,class (:foreground ,inconfidente14))))
    `(magit-diffstat-removed ((,class (:foreground ,inconfidente11))))
    `(magit-hash ((,class (:foreground ,inconfidente8))))
    `(magit-hunk-heading ((,class (:foreground ,inconfidente9))))
    `(magit-hunk-heading-highlight ((,class (:foreground ,inconfidente9 :background ,inconfidente2))))
    `(magit-item-highlight ((,class (:foreground ,inconfidente8 :background ,inconfidente2))))
    `(magit-log-author ((,class (:foreground ,inconfidente7))))
    `(magit-process-ng ((,class (:foreground ,inconfidente13 :weight bold))))
    `(magit-process-ok ((,class (:foreground ,inconfidente14 :weight bold))))
    `(magit-section-heading ((,class (:foreground ,inconfidente7 :weight bold))))
    `(magit-section-highlight ((,class (:background ,inconfidente2))))

    ;; > MU4E
    `(mu4e-header-marks-face ((,class (:foreground ,inconfidente9))))
    `(mu4e-title-face ((,class (:foreground ,inconfidente8))))
    `(mu4e-header-key-face ((,class (:foreground ,inconfidente8))))
    `(mu4e-highlight-face ((,class (:highlight))))
    `(mu4e-flagged-face ((,class (:foreground ,inconfidente13))))
    `(mu4e-unread-face ((,class (:foreground ,inconfidente13 :weight bold))))
    `(mu4e-link-face ((,class (:underline t))))

    ;; > Powerline
    `(powerline-active1 ((,class (:foreground ,inconfidente4 :background ,inconfidente1))))
    `(powerline-active2 ((,class (:foreground ,inconfidente4 :background ,inconfidente3))))
    `(powerline-inactive1 ((,class (:background ,inconfidente2))))
    `(powerline-inactive2 ((,class (:background ,inconfidente2))))

    ;; > Powerline Evil
    `(powerline-evil-base-face ((,class (:foreground ,inconfidente4))))
    `(powerline-evil-normal-face ((,class (:background ,inconfidente8))))
    `(powerline-evil-insert-face ((,class (:foreground ,inconfidente0 :background ,inconfidente4))))
    `(powerline-evil-visual-face ((,class (:foreground ,inconfidente0 :background ,inconfidente7))))
    `(powerline-evil-replace-face ((,class (:foreground ,inconfidente0 :background ,inconfidente9))))

    ;; > NeoTree
    `(neo-banner-face ((,class (:foreground ,inconfidente10))))
    `(neo-dir-link-face ((,class (:foreground ,inconfidente9))))
    `(neo-expand-btn-face ((,class (:foreground ,inconfidente6 :bold t))))
    `(neo-file-link-face ((,class (:foreground ,inconfidente4))))
    `(neo-root-dir-face ((,class (:foreground ,inconfidente7 :weight bold))))
    `(neo-vc-added-face ((,class (:foreground ,inconfidente14))))
    `(neo-vc-conflict-face ((,class (:foreground ,inconfidente11))))
    `(neo-vc-default-face ((,class (:foreground ,inconfidente4))))
    `(neo-vc-edited-face ((,class (:foreground ,inconfidente13))))
    `(neo-vc-ignored-face ((,class (:foreground ,inconfidente3))))
    `(neo-vc-missing-face ((,class (:foreground ,inconfidente12))))
    `(neo-vc-needs-merge-face ((,class (:background ,inconfidente12 :foreground ,inconfidente4))))
    `(neo-vc-needs-update-face ((,class (:background ,inconfidente10 :foreground ,inconfidente4))))
    `(neo-vc-removed-face ((,class (:foreground ,inconfidente11 :strike-through nil))))
    `(neo-vc-up-to-date-face ((,class (:foreground ,inconfidente4))))
    `(neo-vc-user-face ((,class (:foreground ,inconfidente4))))

    ;; > Cider
    `(cider-result-overlay-face ((t (:background unspecified))))

    ;; > Org
    `(org-level-1 ((,class (:foreground ,inconfidente7 :weight extra-bold))))
    `(org-level-2 ((,class (:foreground ,inconfidente8 :weight bold))))
    `(org-level-3 ((,class (:foreground ,inconfidente9 :weight semi-bold))))
    `(org-level-4 ((,class (:foreground ,inconfidente10 :weight normal))))
    `(org-level-5 ((,class (:inherit org-level-4))))
    `(org-level-6 ((,class (:inherit org-level-4))))
    `(org-level-7 ((,class (:inherit org-level-4))))
    `(org-level-8 ((,class (:inherit org-level-4))))
    `(org-agenda-structure ((,class (:foreground ,inconfidente9))))
    `(org-agenda-date ((,class (:foreground ,inconfidente8 :underline nil))))
    `(org-agenda-done ((,class (:foreground ,inconfidente14))))
    `(org-agenda-dimmed-todo-face ((,class (:background ,inconfidente13))))
    `(org-block ((,class (:foreground ,inconfidente4))))
    `(org-block-background ((,class (:background ,inconfidente0))))
    `(org-block-begin-line ((,class (:foreground ,inconfidente7))))
    `(org-block-end-line ((,class (:foreground ,inconfidente7))))
    `(org-checkbox ((,class (:foreground ,inconfidente9))))
    `(org-checkbox-statistics-done ((,class (:foreground ,inconfidente14))))
    `(org-checkbox-statistics-todo ((,class (:foreground ,inconfidente13))))
    `(org-code ((,class (:foreground ,inconfidente7))))
    `(org-column ((,class (:background ,inconfidente2))))
    `(org-column-title ((,class (:inherit org-column :weight bold :underline t))))
    `(org-date ((,class (:foreground ,inconfidente8))))
    `(org-document-info ((,class (:foreground ,inconfidente4))))
    `(org-document-info-keyword ((,class (:foreground ,inconfidente3 :weight bold))))
    `(org-document-title ((,class (:foreground ,inconfidente8 :weight bold))))
    `(org-done ((,class (:foreground ,inconfidente14 :weight bold))))
    `(org-ellipsis ((,class (:foreground ,inconfidente3))))
    `(org-footnote ((,class (:foreground ,inconfidente8))))
    `(org-formula ((,class (:foreground ,inconfidente9))))
    `(org-hide ((,class (:foreground ,inconfidente0 :background ,inconfidente0))))
    `(org-link ((,class (:underline t))))
    `(org-scheduled ((,class (:foreground ,inconfidente14))))
    `(org-scheduled-previously ((,class (:foreground ,inconfidente13))))
    `(org-scheduled-today ((,class (:foreground ,inconfidente8))))
    `(org-special-keyword ((,class (:foreground ,inconfidente9))))
    `(org-table ((,class (:foreground ,inconfidente9))))
    `(org-todo ((,class (:foreground ,inconfidente13 :weight bold))))
    `(org-upcoming-deadline ((,class (:foreground ,inconfidente12))))
    `(org-warning ((,class (:foreground ,inconfidente13 :weight bold))))
    `(font-latex-bold-face ((,class (:inherit bold))))
    `(font-latex-italic-face ((,class (:slant italic))))
    `(font-latex-string-face ((,class (:foreground ,inconfidente14))))
    `(font-latex-match-reference-keywords ((,class (:foreground ,inconfidente9))))
    `(font-latex-match-variable-keywords ((,class (:foreground ,inconfidente4))))
    `(ido-only-match ((,class (:foreground ,inconfidente8))))
    `(org-sexp-date ((,class (:foreground ,inconfidente7))))
    `(ido-first-match ((,class (:foreground ,inconfidente8 :weight bold))))
    `(ido-subdir ((,class (:foreground ,inconfidente9))))
    `(org-quote ((,class (:inherit org-block :slant italic))))
    `(org-verse ((,class (:inherit org-block :slant italic))))
    `(org-agenda-date-weekend ((,class (:foreground ,inconfidente9))))
    `(org-agenda-date-today ((,class (:foreground ,inconfidente8 :weight bold))))
    `(org-agenda-done ((,class (:foreground ,inconfidente14))))
    `(org-verbatim ((,class (:foreground ,inconfidente7))))

    ;; > ivy-mode
    `(ivy-current-match ((,class (:inherit region))))
    `(ivy-minibuffer-match-face-1 ((,class (:inherit default))))
    `(ivy-minibuffer-match-face-2 ((,class (:background ,inconfidente7 :foreground ,inconfidente0))))
    `(ivy-minibuffer-match-face-3 ((,class (:background ,inconfidente8 :foreground ,inconfidente0))))
    `(ivy-minibuffer-match-face-4 ((,class (:background ,inconfidente9 :foreground ,inconfidente0))))
    `(ivy-remote ((,class (:foreground ,inconfidente14))))
    `(ivy-posframe ((,class (:background ,inconfidente1))))
    `(ivy-posframe-border ((,class (:background ,inconfidente1))))
    `(ivy-remote ((,class (:foreground ,inconfidente14))))

    ;; > perspective
    `(persp-selected-face ((,class (:foreground ,inconfidente8 :weight bold))))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
    (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'inconfidente)