theme = "inconfidente-dark"

[editor]
auto-format = true
auto-info = true
auto-pairs = true
bufferline = "multiple"
cursorline = true
insert-final-newline= false
line-number = "relative"
mouse = true
rulers = [ 90 ]
scroll-lines = 1
shell = [ "fish", "-c" ]
true-color = true
undercurl = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.indent-guides]
render = true
skip-levels = 0

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""

[editor.statusline]
mode.normal = "∀"
mode.insert = "↪"
mode.select = "↠"
separator = "⋮"
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "file-type",
  "total-line-numbers",
  "file-encoding"
]
center = []
right = [
  "selections",
  "primary-selection-length",
  "position",
  "position-percentage",
  "spacer",
  "diagnostics",
  "workspace-diagnostics"
]

[keys.normal]
esc = [ "collapse_selection", "keep_primary_selection" ]
A-g = [ ":new", ":insert-output gitui", ":buffer-close!", ":redraw" ]
A-k = [ ":new", ":insert-output k9s", ":buffer-close!", ":redraw" ]
A-w = [ ":pipe sed 's/[ \t]*$//'" ]
C-p = [ "move_line_up", "scroll_up" ]
C-n = [ "move_line_down", "scroll_down" ]

[keys.normal.space]
"." = "file_picker_in_current_buffer_directory"
w = ":write"
q = ":quit"
x = ":buffer-close"
n = "signature_help"

[keys.select.space]
"|" = ":pipe-to"
