COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
MAKEOPTS="-j5"

USE="-bindist -systemd -pulseaudio -cups \
   -dvd -dvdr -cdda -cddr -kde -qt4 -qt5 \
   bluetooth dbus gnome gtk pulseaudio elogind \
   X dbus networkmanager offensive"

PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

LC_MESSAGES=C

ACCEPT_LICENSE="*"

GENTOO_MIRRORS="https://gentoo.c3sl.ufpr.br/ http://gentoo.c3sl.ufpr.br/ rsync://gentoo.c3sl.ufpr.br/gentoo/"

FEATURES="ccache"
CCACHE_DIR="/var/cache/ccache"

L10N="pt-BR"
